swagger: "2.0"
info:
  version: "1.0.0"
  title: Simple node API
host: localhost:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/print:
    get:
      description: Get the 
      parameters:
        name: min
        in: query
        name: max
        in: query
  